import { Category } from "./types";

interface FeedSource {
  url: string;
  name: string;
  category: Category;
}

export const FEED_SOURCES: FeedSource[] = [
  // ── World (30) ─────────────────────────────────────────
  { url: "https://feeds.bbci.co.uk/news/world/rss.xml", name: "BBC News", category: "world" },
  { url: "https://feeds.reuters.com/Reuters/worldNews", name: "Reuters", category: "world" },
  { url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml", name: "New York Times", category: "world" },
  { url: "https://feeds.washingtonpost.com/rss/world", name: "Washington Post", category: "world" },
  { url: "https://www.aljazeera.com/xml/rss/all.xml", name: "Al Jazeera", category: "world" },
  { url: "https://feeds.npr.org/1004/rss.xml", name: "NPR", category: "world" },
  { url: "https://www.theguardian.com/world/rss", name: "The Guardian", category: "world" },
  { url: "https://feeds.abcnews.com/abcnews/internationalheadlines", name: "ABC News", category: "world" },
  { url: "https://rss.cnn.com/rss/edition_world.rss", name: "CNN", category: "world" },
  { url: "https://feeds.skynews.com/feeds/rss/world.xml", name: "Sky News", category: "world" },
  { url: "https://www.cbsnews.com/latest/rss/world", name: "CBS News", category: "world" },
  { url: "https://feeds.nbcnews.com/nbcnews/public/world", name: "NBC News", category: "world" },
  { url: "https://www.pbs.org/newshour/feeds/rss/world", name: "PBS NewsHour", category: "world" },
  { url: "https://www.france24.com/en/rss", name: "France 24", category: "world" },
  { url: "https://www3.nhk.or.jp/nhkworld/en/news/feeds/", name: "NHK World", category: "world" },
  { url: "https://www.dw.com/rss/en/top-stories/s-9097", name: "DW News", category: "world" },
  { url: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms", name: "Times of India", category: "world" },
  { url: "https://www.abc.net.au/news/feed/2942460/rss.xml", name: "ABC Australia", category: "world" },
  { url: "https://moxie.foxnews.com/google-publisher/world.xml", name: "Fox News", category: "world" },
  { url: "https://www.independent.co.uk/news/world/rss", name: "The Independent", category: "world" },
  { url: "https://www.telegraph.co.uk/news/rss.xml", name: "The Telegraph", category: "world" },
  { url: "https://feeds.feedburner.com/time/world", name: "TIME", category: "world" },
  { url: "https://www.voanews.com/api/z-qoeekgvq", name: "Voice of America", category: "world" },
  { url: "https://globalnews.ca/feed/", name: "Global News CA", category: "world" },
  { url: "https://www.scmp.com/rss/91/feed", name: "South China Morning Post", category: "world" },
  { url: "https://www.latimes.com/world-nation/rss2.0.xml", name: "LA Times", category: "world" },
  { url: "https://feeds.feedburner.com/ndtvnews-world-news", name: "NDTV", category: "world" },
  { url: "https://www.thehindu.com/news/international/feeder/default.rss", name: "The Hindu", category: "world" },
  { url: "https://www.irishtimes.com/cmlink/news-1.1319192", name: "Irish Times", category: "world" },
  { url: "https://www.jpost.com/rss/rssfeedsfrontpage.aspx", name: "Jerusalem Post", category: "world" },

  // ── Politics (24) ──────────────────────────────────────
  { url: "https://feeds.feedburner.com/politico/politics", name: "Politico", category: "politics" },
  { url: "https://thehill.com/feed/", name: "The Hill", category: "politics" },
  { url: "https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml", name: "NYT Politics", category: "politics" },
  { url: "https://feeds.washingtonpost.com/rss/politics", name: "WaPo Politics", category: "politics" },
  { url: "https://rss.cnn.com/rss/cnn_allpolitics.rss", name: "CNN Politics", category: "politics" },
  { url: "https://feeds.foxnews.com/foxnews/politics", name: "Fox Politics", category: "politics" },
  { url: "https://feeds.npr.org/1014/rss.xml", name: "NPR Politics", category: "politics" },
  { url: "https://feeds.bbci.co.uk/news/politics/rss.xml", name: "BBC Politics", category: "politics" },
  { url: "https://www.realclearpolitics.com/index.xml", name: "RealClearPolitics", category: "politics" },
  { url: "https://feeds.feedburner.com/dailycaller", name: "Daily Caller", category: "politics" },
  { url: "https://www.nationalreview.com/feed/", name: "National Review", category: "politics" },
  { url: "https://theintercept.com/feed/?rss", name: "The Intercept", category: "politics" },
  { url: "https://www.motherjones.com/feed/", name: "Mother Jones", category: "politics" },
  { url: "https://www.dailywire.com/feeds/rss.xml", name: "Daily Wire", category: "politics" },
  { url: "https://www.salon.com/feed/", name: "Salon", category: "politics" },
  { url: "https://feeds.feedburner.com/breitbart", name: "Breitbart", category: "politics" },
  { url: "https://www.commondreams.org/feeds/feed.rss", name: "Common Dreams", category: "politics" },
  { url: "https://www.theguardian.com/us-news/rss", name: "Guardian US", category: "politics" },
  { url: "https://www.axios.com/feeds/feed.rss", name: "Axios", category: "politics" },
  { url: "https://talkingpointsmemo.com/feed", name: "Talking Points Memo", category: "politics" },
  { url: "https://www.cbsnews.com/latest/rss/politics", name: "CBS Politics", category: "politics" },
  { url: "https://abcnews.go.com/abcnews/politicsheadlines", name: "ABC Politics", category: "politics" },
  { url: "https://www.usatoday.com/rss/news/politics/", name: "USA Today Politics", category: "politics" },
  { url: "https://fivethirtyeight.com/feed/", name: "FiveThirtyEight", category: "politics" },

  // ── Tech (20) ──────────────────────────────────────────
  { url: "https://techcrunch.com/feed/", name: "TechCrunch", category: "tech" },
  { url: "https://feeds.arstechnica.com/arstechnica/index", name: "Ars Technica", category: "tech" },
  { url: "https://www.theverge.com/rss/index.xml", name: "The Verge", category: "tech" },
  { url: "https://www.wired.com/feed/rss", name: "Wired", category: "tech" },
  { url: "https://feeds.feedburner.com/TechRadar", name: "TechRadar", category: "tech" },
  { url: "https://www.engadget.com/rss.xml", name: "Engadget", category: "tech" },
  { url: "https://www.zdnet.com/news/rss.xml", name: "ZDNet", category: "tech" },
  { url: "https://www.cnet.com/rss/news/", name: "CNET", category: "tech" },
  { url: "https://feeds.feedburner.com/venturebeat/SZYF", name: "VentureBeat", category: "tech" },
  { url: "https://thenextweb.com/feed/", name: "The Next Web", category: "tech" },
  { url: "https://www.tomshardware.com/feeds/all", name: "Tom's Hardware", category: "tech" },
  { url: "https://9to5mac.com/feed/", name: "9to5Mac", category: "tech" },
  { url: "https://www.macrumors.com/macrumors.xml", name: "MacRumors", category: "tech" },
  { url: "https://9to5google.com/feed/", name: "9to5Google", category: "tech" },
  { url: "https://www.androidcentral.com/feed", name: "Android Central", category: "tech" },
  { url: "https://www.techspot.com/backend/rss/rss.xml", name: "TechSpot", category: "tech" },
  { url: "https://feeds.feedburner.com/Techmeme", name: "Techmeme", category: "tech" },
  { url: "https://www.digitaltrends.com/feed/", name: "Digital Trends", category: "tech" },
  { url: "https://www.theregister.com/headlines.atom", name: "The Register", category: "tech" },
  { url: "https://gizmodo.com/rss", name: "Gizmodo", category: "tech" },

  // ── Business (18) ──────────────────────────────────────
  { url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114", name: "CNBC", category: "business" },
  { url: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml", name: "NYT Business", category: "business" },
  { url: "https://feeds.bloomberg.com/markets/news.rss", name: "Bloomberg", category: "business" },
  { url: "https://www.ft.com/?format=rss", name: "Financial Times", category: "business" },
  { url: "https://feeds.marketwatch.com/marketwatch/topstories/", name: "MarketWatch", category: "business" },
  { url: "https://www.economist.com/finance-and-economics/rss.xml", name: "The Economist", category: "business" },
  { url: "https://feeds.reuters.com/reuters/businessNews", name: "Reuters Business", category: "business" },
  { url: "https://www.wsj.com/xml/rss/3_7085.xml", name: "Wall Street Journal", category: "business" },
  { url: "https://fortune.com/feed/", name: "Fortune", category: "business" },
  { url: "https://feeds.forbes.com/forbes/business/", name: "Forbes", category: "business" },
  { url: "https://feeds.inc.com/incmagazine", name: "Inc.", category: "business" },
  { url: "https://qz.com/feed/", name: "Quartz", category: "business" },
  { url: "https://feeds.feedburner.com/entrepreneur/latest", name: "Entrepreneur", category: "business" },
  { url: "https://www.barrons.com/feed", name: "Barron's", category: "business" },
  { url: "https://feeds.feedburner.com/InvestorPlace", name: "InvestorPlace", category: "business" },
  { url: "https://www.businessinsider.com/rss", name: "Business Insider", category: "business" },
  { url: "https://feeds.feedburner.com/TheMotleyFool", name: "Motley Fool", category: "business" },
  { url: "https://finance.yahoo.com/news/rss/", name: "Yahoo Finance", category: "business" },

  // ── Health (20) ────────────────────────────────────────
  { url: "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml", name: "NYT Health", category: "health" },
  { url: "https://feeds.washingtonpost.com/rss/national/health-science", name: "WaPo Health", category: "health" },
  { url: "https://www.statnews.com/feed/", name: "STAT News", category: "health" },
  { url: "https://feeds.bbci.co.uk/news/health/rss.xml", name: "BBC Health", category: "health" },
  { url: "https://www.theguardian.com/society/health/rss", name: "Guardian Health", category: "health" },
  { url: "https://feeds.npr.org/103537970/rss.xml", name: "NPR Health", category: "health" },
  { url: "https://rss.cnn.com/rss/cnn_health.rss", name: "CNN Health", category: "health" },
  { url: "https://www.medicalnewstoday.com/newsfeeds/rss", name: "Medical News Today", category: "health" },
  { url: "https://www.webmd.com/rss/rss.aspx", name: "WebMD", category: "health" },
  { url: "https://www.healthline.com/rss/health-news", name: "Healthline", category: "health" },
  { url: "https://www.who.int/feeds/entity/mediacentre/news/en/rss.xml", name: "WHO News", category: "health" },
  { url: "https://www.nih.gov/news-events/news-releases/feed", name: "NIH News", category: "health" },
  { url: "https://www.thelancet.com/rssfeed/lancet_current.xml", name: "The Lancet", category: "health" },
  { url: "https://www.bmj.com/rss/recent.xml", name: "BMJ", category: "health" },
  { url: "https://kffhealthnews.org/feed/", name: "KFF Health News", category: "health" },
  { url: "https://www.fiercehealthcare.com/feed", name: "Fierce Healthcare", category: "health" },
  { url: "https://www.everydayhealth.com/rss/", name: "Everyday Health", category: "health" },
  { url: "https://www.livescience.com/feeds/health", name: "Live Science Health", category: "health" },
  { url: "https://feeds.foxnews.com/foxnews/health", name: "Fox Health", category: "health" },
  { url: "https://www.scientificamerican.com/section/health/feed/", name: "SciAm Health", category: "health" },

  // ── Sports (16) ────────────────────────────────────────
  { url: "https://www.espn.com/espn/rss/news", name: "ESPN", category: "sports" },
  { url: "https://feeds.bbci.co.uk/sport/rss.xml", name: "BBC Sport", category: "sports" },
  { url: "https://www.theguardian.com/sport/rss", name: "Guardian Sport", category: "sports" },
  { url: "https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml", name: "NYT Sports", category: "sports" },
  { url: "https://sports.yahoo.com/rss/", name: "Yahoo Sports", category: "sports" },
  { url: "https://www.cbssports.com/rss/headlines/", name: "CBS Sports", category: "sports" },
  { url: "https://www.skysports.com/rss/12040", name: "Sky Sports", category: "sports" },
  { url: "https://www.si.com/.rss/full/", name: "Sports Illustrated", category: "sports" },
  { url: "https://theathletic.com/feeds/rss/news/", name: "The Athletic", category: "sports" },
  { url: "https://www.foxsports.com/rss-feeds", name: "Fox Sports", category: "sports" },
  { url: "https://bleacherreport.com/articles/feed", name: "Bleacher Report", category: "sports" },
  { url: "https://www.nbcsports.com/rss.xml", name: "NBC Sports", category: "sports" },
  { url: "https://www.sbnation.com/rss/index.xml", name: "SB Nation", category: "sports" },
  { url: "https://deadspin.com/rss", name: "Deadspin", category: "sports" },
  { url: "https://www.sportingnews.com/rss", name: "Sporting News", category: "sports" },
  { url: "https://www.usatoday.com/rss/sports/", name: "USA Today Sports", category: "sports" },

  // ── Science (18) ───────────────────────────────────────
  { url: "https://www.nasa.gov/rss/dyn/breaking_news.rss", name: "NASA", category: "science" },
  { url: "https://www.sciencedaily.com/rss/all.xml", name: "Science Daily", category: "science" },
  { url: "https://www.newscientist.com/section/news/feed/", name: "New Scientist", category: "science" },
  { url: "https://www.nature.com/nature.rss", name: "Nature", category: "science" },
  { url: "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml", name: "BBC Science", category: "science" },
  { url: "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml", name: "NYT Science", category: "science" },
  { url: "https://www.sciencemag.org/rss/news_current.xml", name: "Science Magazine", category: "science" },
  { url: "https://phys.org/rss-feed/", name: "Phys.org", category: "science" },
  { url: "https://www.livescience.com/feeds/all", name: "Live Science", category: "science" },
  { url: "https://www.space.com/feeds/all", name: "Space.com", category: "science" },
  { url: "https://www.scientificamerican.com/feed/", name: "Scientific American", category: "science" },
  { url: "https://feeds.feedburner.com/DiscoverMagazine", name: "Discover Magazine", category: "science" },
  { url: "https://www.iflscience.com/feed", name: "IFLScience", category: "science" },
  { url: "https://www.smithsonianmag.com/rss/science-nature/", name: "Smithsonian", category: "science" },
  { url: "https://www.theguardian.com/science/rss", name: "Guardian Science", category: "science" },
  { url: "https://www.popsci.com/feed/", name: "Popular Science", category: "science" },
  { url: "https://feeds.feedburner.com/QuantaMagazine", name: "Quanta Magazine", category: "science" },
  { url: "https://www.atlasobscura.com/feeds/latest", name: "Atlas Obscura", category: "science" },

  // ── Entertainment (18) ─────────────────────────────────
  { url: "https://variety.com/feed/", name: "Variety", category: "entertainment" },
  { url: "https://www.hollywoodreporter.com/feed/", name: "Hollywood Reporter", category: "entertainment" },
  { url: "https://deadline.com/feed/", name: "Deadline", category: "entertainment" },
  { url: "https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml", name: "BBC Entertainment", category: "entertainment" },
  { url: "https://www.theguardian.com/culture/rss", name: "Guardian Culture", category: "entertainment" },
  { url: "https://ew.com/feed/", name: "Entertainment Weekly", category: "entertainment" },
  { url: "https://www.rollingstone.com/feed/", name: "Rolling Stone", category: "entertainment" },
  { url: "https://pitchfork.com/feed/feed-news/rss", name: "Pitchfork", category: "entertainment" },
  { url: "https://www.vulture.com/feed/rss/all/index.xml", name: "Vulture", category: "entertainment" },
  { url: "https://www.indiewire.com/feed/", name: "IndieWire", category: "entertainment" },
  { url: "https://collider.com/feed/", name: "Collider", category: "entertainment" },
  { url: "https://screenrant.com/feed/", name: "Screen Rant", category: "entertainment" },
  { url: "https://www.avclub.com/rss", name: "The A.V. Club", category: "entertainment" },
  { url: "https://www.nme.com/feed", name: "NME", category: "entertainment" },
  { url: "https://consequenceofsound.net/feed/", name: "Consequence of Sound", category: "entertainment" },
  { url: "https://www.stereogum.com/feed/", name: "Stereogum", category: "entertainment" },
  { url: "https://www.thewrap.com/feed/", name: "TheWrap", category: "entertainment" },
  { url: "https://www.complex.com/feed/", name: "Complex", category: "entertainment" },

  // ── Opinion (20) ───────────────────────────────────────
  { url: "https://rss.nytimes.com/services/xml/rss/nyt/Opinion.xml", name: "NYT Opinion", category: "opinion" },
  { url: "https://feeds.washingtonpost.com/rss/opinions", name: "WaPo Opinions", category: "opinion" },
  { url: "https://www.theguardian.com/commentisfree/rss", name: "Guardian Opinion", category: "opinion" },
  { url: "https://www.wsj.com/xml/rss/3_7041.xml", name: "WSJ Opinion", category: "opinion" },
  { url: "https://www.newyorker.com/feed/news", name: "The New Yorker", category: "opinion" },
  { url: "https://www.vox.com/rss/index.xml", name: "Vox", category: "opinion" },
  { url: "https://www.theatlantic.com/feed/all/", name: "The Atlantic", category: "opinion" },
  { url: "https://nymag.com/feed/rss/all/index.xml", name: "New York Magazine", category: "opinion" },
  { url: "https://www.spectator.co.uk/feed/", name: "The Spectator", category: "opinion" },
  { url: "https://www.thenation.com/feed/", name: "The Nation", category: "opinion" },
  { url: "https://www.jacobinmag.com/feed/", name: "Jacobin", category: "opinion" },
  { url: "https://www.americanconservative.com/feed/", name: "American Conservative", category: "opinion" },
  { url: "https://reason.com/feed/", name: "Reason", category: "opinion" },
  { url: "https://www.currentaffairs.org/feed", name: "Current Affairs", category: "opinion" },
  { url: "https://www.slate.com/feeds/all.rss", name: "Slate", category: "opinion" },
  { url: "https://www.newsweek.com/rss", name: "Newsweek", category: "opinion" },
  { url: "https://www.thedailybeast.com/rss", name: "Daily Beast", category: "opinion" },
  { url: "https://unherd.com/feed/", name: "UnHerd", category: "opinion" },
  { url: "https://www.prospect.org/feed", name: "American Prospect", category: "opinion" },
  { url: "https://quillette.com/feed/", name: "Quillette", category: "opinion" },

  // ── Reddit ────────────────────────────────────────────
  { url: "https://www.reddit.com/r/worldnews/.rss", name: "r/worldnews", category: "world" },
  { url: "https://www.reddit.com/r/news/.rss", name: "r/news", category: "world" },
  { url: "https://www.reddit.com/r/politics/.rss", name: "r/politics", category: "politics" },
  { url: "https://www.reddit.com/r/technology/.rss", name: "r/technology", category: "tech" },
  { url: "https://www.reddit.com/r/business/.rss", name: "r/business", category: "business" },
  { url: "https://www.reddit.com/r/economics/.rss", name: "r/economics", category: "business" },
  { url: "https://www.reddit.com/r/health/.rss", name: "r/health", category: "health" },
  { url: "https://www.reddit.com/r/sports/.rss", name: "r/sports", category: "sports" },
  { url: "https://www.reddit.com/r/science/.rss", name: "r/science", category: "science" },
  { url: "https://www.reddit.com/r/space/.rss", name: "r/space", category: "science" },
  { url: "https://www.reddit.com/r/entertainment/.rss", name: "r/entertainment", category: "entertainment" },
  { url: "https://www.reddit.com/r/movies/.rss", name: "r/movies", category: "entertainment" },
];
